spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/ticket_web
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
debug: true